{{- $kafkaHost := ( .Values.config.kafka_host | replace "$release_name" .Release.Name ) -}}
{{- $redisHost := ( .Values.config.redis_host | replace "$release_name" .Release.Name ) -}}
{{- $simulatorHost := ( .Values.config.simulator_host | replace "$release_name" .Release.Name ) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "poc-modules.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "poc-modules.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "poc-modules.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "poc-modules.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/port: "{{ .Values.service.internalPort }}"
        prometheus.io/scrape: "true"
      {{- end }}
    spec:
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      {{- if .Values.init.enabled }}
      initContainers:
        - name: {{ .Values.init.image.name }}
          image: {{ .Values.init.image.repository }}:{{ .Values.init.image.tag }}
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          command:
            - sh
            - "-c"
            - {{ (.Values.init.image.command | replace "$kafka_host" $kafkaHost | replace "$kafka_port" (printf "%.0f" .Values.config.kafka_port) ) | quote }}
          env:
          {{- range $envItem := .Values.init.image.env }}
          - name: {{ $envItem.name }}
            value: {{ $envItem.value }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.imagePullSecrets }}
          imagePullSecrets:
          {{ toYaml .Values.image.imagePullSecrets | indent 10 }}
          {{- end }}
          command:
            - sh
            - "-c"
            - {{ .Values.image.command | quote }}
          args: {{ .Values.image.args }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}
          # volumeMounts:
          #   - name: {{ template "poc-modules.fullname" . }}-config-volume
          #     mountPath: /opt/poc-participants/config
          env:
            - name: LOG_LEVEL
              value: {{ .Values.config.log_level | quote}}
            - name: LOG_FILTER
              value: {{ .Values.config.log_filter | quote}}
            - name: CSL_LOG_TRANSPORT
              value: {{ .Values.config.log_transport | quote}}
            - name: KAFKA_HOST
              value: "{{ $kafkaHost }}:{{ .Values.config.kafka_port }}"
            - name: REDIS_HOST
              value: {{ $redisHost | quote }}
            - name: SIMULATOR_HOST
              value: {{ $simulatorHost | quote }}
            - name: KAFKA_CONSUMER
              value: {{ .Values.config.kafka_consumer | quote }}
            - name: KAFKA_PRODUCER
              value: {{ .Values.config.kafka_producer | quote }}
            - name: KAFKAJS_PRODUCER_GZIP
              value: {{ .Values.config.kafka_producer_gzip | quote }}
            - name: KAFKA_AUTO_COMMIT
              value: {{ .Values.config.kafka_autocommit | quote }}
            - name: KAFKA_AUTO_COMMIT_INTERVAL
              value: {{ .Values.config.kafka_autocommit_interval | quote }}
            - name: KAFKA_AUTO_COMMIT_THRESHOLD
              value: {{ .Values.config.kafka_autocommit_threshold | quote }}
            - name: UV_THREADPOOL_SIZE
              value: {{ .Values.config.uv_threadpool_size | quote }}

      # volumes:
      #   - name: {{ template "poc-modules.fullname" . }}-config-volume
      #     configMap:
      #       name: {{ template "poc-modules.fullname" . }}-config
      #       items:
      #       - key: default.json
      #         path: default.json
