# Default values for ml-api-adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: mojaloop/poc-architecture
  tag: v0.1
  command: '["node", "src/api/index.js"]'

config:
  # this can be set if the dependency chart for kafka is disabled. If 'kafka_host' is commented out, then the name of the dependency chart will be used.
  kafka_host: '$release_name-kafka'
  kafka_port: 9092
  kafka_autocommit: false
  simulator_host: '$release_name-simulator'
  uv_threadpool_size: 7
  redis_host: 'redis://$release_name-redis-master:6379'
  log_level: debug

init:
  enabled: true
  image:
    name: wait-for-kafka
    repository: solsson/kafka
    tag: latest
    pullPolicy: Always
    command: "until ./bin/kafka-broker-api-versions.sh --bootstrap-server $kafka_host:$kafka_port; do echo waiting for Kafka; sleep 2; done;"
    env: {}

readinessProbe:
  enabled: false
  httpGet:
    path: /health
  initialDelaySeconds: 120
  periodSeconds: 15
livenessProbe:
  enabled: false
  httpGet:
    path: /health
  initialDelaySeconds: 90
  periodSeconds: 15

## metric configuration for prometheus instrumentation
metrics:
  ## flag to enable/disable the metrics end-points
  enabled: false
  config:
    timeout: 5000
    prefix: moja_
    defaultLabels:
      serviceName: poc-participants-service

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

