# Default values for ml-api-adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: mojaloop/poc-architecture
  tag: v0.28
  command: 'cd modules/transfers && node dist/application/index.js handler --config ../../.env'

config:
  # this can be set if the dependency chart for kafka is disabled. If 'kafka_host' is commented out, then the name of the dependency chart will be used.
  kafka_host: '$release_name-kafka'
  kafka_port: 9092
  # Supported consumers: kafkajs, node-kafka, node-kafka-stream, node-rdkafka
  kafka_consumer: node-rdkafka
  # Supported producers: kafkajs, node-kafka, node-rdkafka
  kafka_producer: node-rdkafka
  kafka_producer_gzip: false
  kafka_autocommit: false
  kafka_autocommit_interval: 100
  kafka_autocommit_threshold: 1000
  # Supported commit modes: no-wait, commit-msg-sync (blocking)
  rdkafka_commit_wait_mode: commit-msg-sync
  rdkafka_batch_num_messages: null
  rdkafka_queue_buffering_max_us: null
  measure_kafka_group_id: ''
  simulator_host: '$release_name-legacy-simulator'
  uv_threadpool_size: 7
  redis_host: 'redis://$release_name-redis-master:6379'
  redis_expiration_in_sec: 1800
  redis_duplicate_host: 'redis://$release_name-redis-master:6379'
  # Supported repo Types: memory, redis, cachedredis
  participants_repo_type: redis
  event_trace_vendor: mojaloop
  log_level: info
  log_filter: info

init:
  enabled: true
  image:
    name: wait-for-kafka
    repository: solsson/kafka
    tag: latest
    pullPolicy: Always
    command: "until ./bin/kafka-broker-api-versions.sh --bootstrap-server $kafka_host:$kafka_port; do echo waiting for Kafka; sleep 2; done;"
    env: {}

readinessProbe:
  enabled: false
  httpGet:
    path: /health
  initialDelaySeconds: 60
  periodSeconds: 15
livenessProbe:
  enabled: false
  httpGet:
    path: /health
  initialDelaySeconds: 30
  periodSeconds: 15

## metric configuration for prometheus instrumentation
metrics:
  ## flag to enable/disable the metrics end-points
  enabled: false
  config:
    timeout: 5000
    prefix: moja_
    defaultLabels:
      serviceName: poc-participants-service

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

